# Generated by Django 5.1.1 on 2025-11-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcreation',
            name='owner',
        ),
    ]
