# Generated by Django 5.1.1 on 2025-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=30)),
                ('Preferred_size', models.IntegerField(default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Phone', models.IntegerField(default=0, max_length=30)),
                ('Email_Address', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='size_range',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
