# Generated by Django 5.1.1 on 2025-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Website', '0002_order_profile_products_size_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Preferred_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
    ]
