# Generated by Django 5.1.1 on 2025-11-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Website', '0003_alter_order_preferred_size_alter_products_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
