# Generated by Django 5.1.1 on 2025-11-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Website', '0004_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desription',
            new_name='description',
        ),
    ]
