# Generated by Django 5.1.1 on 2025-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODOLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work', models.CharField(max_length=200)),
                ('Time', models.TextField(max_length=40)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
